#This is a script for manipulating a spreadsheet presenting all useful summary statistics from
#experimental and theoretical networks. This is the last step in the automation of video/paramter inputs
#to get out a comprehensive data frame with all this data summarised.

#The tables imported here come from 
#namesOfFiles-spreadsheetCuration.sh 
#namesOfPaths-spreadsheetCuration.sh
#numberOfLines-spreadsheetCuration.sh
#statisticsLists-spreadsheetCuration.sh

#NamesOfFiles and NamesOfPaths are generated to ENSURE the consistency of the order the statistics are 'found' in using bash 'find'
#will need to eyeball these tables each time this statistics table is generated- if each row is not pulled from the same sim/video, the whole table 
#will be inaccurate. 


#eyeball THESE
#can use pathsOrder[n,] to scan through the rows easily and check all routes are to the same directory
filesOrder<-read.delim("/Users/d1795494/Documents/PIPELINE/OriginFilesTable.txt",sep=" ",header=FALSE)
pathsOrder<-read.delim("/Users/d1795494/Documents/PIPELINE/OriginPathsTable.txt",sep=" ",header=FALSE)

#statistics import
#statsTable<-read.delim("/Users/d1795494/Documents/PIPELINE/StatsTable.txt",sep=" ",header=FALSE)
#statsTable<-read.delim("/Users/d1795494/Documents/PIPELINE/StatsTable-earlypoint.txt",sep=" ",header=FALSE)
statsTable<-read.delim("/Users/d1795494/Documents/PIPELINE/StatsTable-midpoint.txt",sep=" ",header=FALSE)

#Include theoretical/simulation distinguishers
#number of theoreticals is nrow-45 as we have 45 experimental videos currently used. But also have two experimentals (from other's publications) stuck on the end so add that.
numberOfTheoreticals<-nrow(statsTable)-(45+2)
typeString<-c(rep("Experimental",45),rep("Theoretical",numberOfTheoreticals),"Experimental","Experimental")
statsTable$Type<-typeString

#Include ID labels
#I've included the order from the old stat tabel to correspond with the order of this table, so previous morphospace diagrams aren't redundantly labelled
#GFP= wt, F= FRIENDLY, S=simulation, NM=null models, BM=biologically motivated, SD=stripped down, RC= random choice
###oldTableOrder<-c("GFP1","GFP4","GFP3","GFP6","GFP7","GFP5","GFP2","GFP8","F4","F2","F5","F1","F6","F3","F7","S4","S8","S5","S2","S6","S7","S1","NM3","NM4","NM7","NM8","NM9","NM10","NM5","NM6","NM1","NM2")
###NewTheoreticals<-c("BM1","BM2","BM3","BM4","BM5","BM6","BM7","BM8","BM9","BM10","SD1","SD2","SD3","SD4","SD5","SD6","SD7","SD8","SD9","SD10","SD11","SD12","SD13","SD14","RC1","RC2","RC3","RC4")
###labelString<-c(oldTableOrder,NewTheoreticals)
#8-7-20 just altered the NM7/8 order. 7 is now steppara=0.010, not 0.990 now. 
newestOrder<-c("GFP1","GFP01","GFP2","GFP02","GFP3","GFP03","GFP4","GFP04","GFP5","GFP6","GFP7",
               "GFP8","GFP05","GFP9","GFP06","GFP07","GFP08","GFP09","GFP10","GFP11","GFP010","GFP12",
               "GFP011","F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12","F13","F14","F15",
               "F16","F17","F18","F19","F01","F20","F21","S4","S8","S5","S2","S6","S7","S1","NM3","NM4",
               "NM8","NM7","NM9","NM11","NM10","NM5","NM6","NM1","NM2","NM12","BM1","BM2","BM3","BM4","BM5","BM6",
               "BM7","BM8","BM9","BM10","ST1","ST2","ST3","ST4","ST5","ST6","ST7","ST8","ST9","ST10","ST11",
               "ST12","ST13","ST14","R1","R2","R3","R4","R5","R6","R7","R8","R9","R10","R11","INDVID1","INDVID2")

statsTable$Label<-newestOrder

#Add the names of files in, to check down the line which is which
#need to remove empty elements generated by the extra intervals files (CH and assocTime)
statsTable$FileName <- filesOrder$V1[filesOrder$V1 != ""]

#Name columns
colnames(statsTable)<-c("FrameNocollation","CCcollation","propMaxCCcollation","normPropMaxCCcollation","MaxMincollation","normMaxMincollation","percolationCollation","walkerDegreeCollation","meanDegreeCollation","cvDegreeCollation","meanInterMitoDistCollation","cvInterMitoDistCollation","meanSpeedCollation","maxCHCollation","minCHCollation","meanCHCollation","cvCHCollation","assocTimeCollation","maxCHRateCollation","minCHRateCollation","meanCHRateCollation","cvCHRateCollation","AverageDistscollation","avConnectedNeighbours","NetworkEfficiencyCollation","Type","Label","FileName")
# reorder by column name
statsTable <- statsTable[c("FileName","Type","Label","FrameNocollation","CCcollation","propMaxCCcollation","normPropMaxCCcollation","MaxMincollation","normMaxMincollation","percolationCollation","walkerDegreeCollation","meanDegreeCollation","cvDegreeCollation","meanInterMitoDistCollation","cvInterMitoDistCollation","meanSpeedCollation","maxCHCollation","minCHCollation","meanCHCollation","cvCHCollation","assocTimeCollation","maxCHRateCollation","minCHRateCollation","meanCHRateCollation","cvCHRateCollation","AverageDistscollation","avConnectedNeighbours","NetworkEfficiencyCollation")]


#Export 
write.csv(statsTable,"/Users/d1795494/Documents/PIPELINEdocs/SIMSTATSTABLE-midframe-24-8-20.csv")

