find PIPELINE/mitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_F.csv" > PIPELINE/pathlistF.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_CC.csv" > PIPELINE/pathlistCC.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_SCCproportions.csv" > PIPELINE/pathlistSCCprop.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_normSCCproportions.csv" > PIPELINE/pathlistnormSCCprop.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "normalisedAndRawMaxMinDistsForAllFrames.csv" > PIPELINE/pathlistmaxmin.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "percolationThresholdJumps*.csv" > PIPELINE/pathlistpercolation.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "MeanDropsBetweenStepsForAllFramesIn*.csv" > PIPELINE/pathlistwalkerdegree.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_MeanD_WS.csv" > PIPELINE/pathlistmeandegree.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_CoeffVarD_WS.csv" > PIPELINE/pathlistcvdegree.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "summaryStatsInterMitoDist*" > PIPELINE/pathlistintermito.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "averageOverAllSpeedsAllFrames.csv" > PIPELINE/pathlistmeanspeed.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStats_*" > PIPELINE/pathlistCH.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "associationtimeMeanIn*" > PIPELINE/pathlistassoctime.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "averageDistsOverNetworksForAllFrames_WS.csv" > PIPELINE/pathlistaverageDists.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "ConvexHullSummStatsAsRate_*" > PIPELINE/pathlistCHRatelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "*_averageNumberOfConnectedNeighbours.csv" > PIPELINE/pathlistaverageNumberOfConnectedNeighbours.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "avNetworkEfficiency_WS.csv" > PIPELINE/pathlistNetworkEfficiency.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "summaryStatsAccumulatesOverAllFramesInterMitoDist*" > PIPELINE/pathlistaverageInterMitoDistINTERVALS.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "speedMeansOverAllFrames*" > PIPELINE/pathlistspeedmeansINTERVALS.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "ConvexHullSummStatsFromFrame*" > PIPELINE/pathlistconvexhullsINTERVALS.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "associationtimesIntrvls*" > PIPELINE/pathlistassociationtimesINTERVALS.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "associationtimeIntervalsMeanIn*" > PIPELINE/pathlistassociationtimesMeanINTERVALS.txt

paste -d' '  PIPELINE/pathlistF.txt PIPELINE/pathlistCC.txt  PIPELINE/pathlistSCCprop.txt  PIPELINE/pathlistnormSCCprop.txt  PIPELINE/pathlistmaxmin.txt  PIPELINE/pathlistpercolation.txt  PIPELINE/pathlistwalkerdegree.txt  PIPELINE/pathlistmeandegree.txt  PIPELINE/pathlistcvdegree.txt  PIPELINE/pathlistintermito.txt  PIPELINE/pathlistmeanspeed.txt  PIPELINE/pathlistCH.txt  PIPELINE/pathlistassoctime.txt  PIPELINE/pathlistaverageDists.txt  PIPELINE/pathlistCHRatelist.txt PIPELINE/pathlistaverageNumberOfConnectedNeighbours.txt PIPELINE/pathlistNetworkEfficiency.txt PIPELINE/pathlistaverageInterMitoDistINTERVALS.txt PIPELINE/pathlistspeedmeansINTERVALS.txt PIPELINE/pathlistconvexhullsINTERVALS.txt PIPELINE/pathlistassociationtimesINTERVALS.txt PIPELINE/pathlistassociationtimesMeanINTERVALS.txt > PIPELINE/OriginPathsTable.txt
