find PIPELINE/mitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_F.csv" | xargs -n1 basename > PIPELINE/Ffilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_CC.csv" | xargs -n1 basename > PIPELINE/CCfilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_SCCproportions.csv" | xargs -n1 basename > PIPELINE/SCCpropfilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_normSCCproportions.csv" | xargs -n1 basename > PIPELINE/normSCCpropfilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "normalisedAndRawMaxMinDistsForAllFrames.csv" | xargs -n1 basename > PIPELINE/maxminfilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "percolationThresholdJumps*.csv" | xargs -n1 basename > PIPELINE/percolationfilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "MeanDropsBetweenStepsForAllFramesIn*.csv" | xargs -n1 basename > PIPELINE/walkerdegreefilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_MeanD_WS.csv" | xargs -n1 basename > PIPELINE/meandegreefilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_CoeffVarD_WS.csv" | xargs -n1 basename > PIPELINE/cvdegreefilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "summaryStatsInterMitoDist*" | xargs -n1 basename > PIPELINE/intermitofilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "averageOverAllSpeedsAllFrames.csv" | xargs -n1 basename > PIPELINE/meanspeedfilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStats_*" | xargs -n1 basename > PIPELINE/CHfilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "associationtimeMeanIn*" | xargs -n1 basename > PIPELINE/assoctimefilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "averageDistsOverNetworksForAllFrames_WS.csv" | xargs -n1 basename > PIPELINE/averageDistsfilelist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStatsAsRate_*" | xargs -n1 basename > PIPELINE/CHRatefilellist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_averageNumberOfConnectedNeighbours.csv"| xargs -n1 basename > PIPELINE/averageNumberOfConnectedNeighboursfilellist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "avNetworkEfficiency_WS.csv" | xargs -n1 basename > PIPELINE/NetworkEfficiencyfilelist.txt

find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "summaryStatsAccumulatesOverAllFramesInterMitoDist*" > PIPELINE/averageInterMitoDistINTERVALSfilellist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "speedMeansOverAllFrames*" > PIPELINE/speedmeansINTERVALSfilellist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "ConvexHullSummStatsFromFrame*" > PIPELINE/convexhullsINTERVALSfilellist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "associationtimesIntrvls*" > PIPELINE/associationtimesINTERVALSfilellist.txt
find PIPELINE/MitoGFP-TRACKMATERUNS PIPELINE/FRIENDLY-TRACKMATERUNS PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE  -name "associationtimeIntervalsMeanIn*" > PIPELINE/associationtimesMeanINTERVALSfilelist.txt

paste -d' ' PIPELINE/Ffilelist.txt PIPELINE/CCfilelist.txt PIPELINE/SCCpropfilelist.txt PIPELINE/normSCCpropfilelist.txt PIPELINE/maxminfilelist.txt PIPELINE/percolationfilelist.txt PIPELINE/walkerdegreefilelist.txt PIPELINE/meandegreefilelist.txt PIPELINE/cvdegreefilelist.txt PIPELINE/intermitofilelist.txt PIPELINE/meanspeedfilelist.txt PIPELINE/CHfilelist.txt PIPELINE/assoctimefilelist.txt PIPELINE/averageDistsfilelist.txt PIPELINE/CHRatefilellist.txt PIPELINE/averageNumberOfConnectedNeighboursfilellist.txt PIPELINE/NetworkEfficiencyfilelist.txt PIPELINE/averageInterMitoDistINTERVALSfilellist.txt PIPELINE/speedmeansINTERVALSfilellist.txt PIPELINE/convexhullsINTERVALSfilellist.txt PIPELINE/associationtimesINTERVALSfilellist.txt PIPELINE/associationtimesMeanINTERVALSfilelist.txt > PIPELINE/OriginFilesTable.txt

