#This script goes through all directories you want to be searching in, fins all approriately named files, and exracts the last frames', or overall statistics from them.

find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_F.csv" | xargs -n1 awk -F "," 'END{print $1}'  > PIPELINE/FrameNocollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_CC.csv" | xargs -n1 awk -F "," 'END{print $2}'  > PIPELINE/CCcollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_SCCproportions.csv" | xargs -n1 awk -F "," 'END{print $2}'> PIPELINE/propMaxCCcollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_normSCCproportions.csv" | xargs -n1 awk -F "," 'END{print $2}'> PIPELINE/normPropMaxCCcollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "normalisedAndRawMaxMinDistsForAllFrames.csv" | xargs -n1 awk -F "," 'END{print $2}'> PIPELINE/MaxMincollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "normalisedAndRawMaxMinDistsForAllFrames.csv" | xargs -n1 awk -F "," 'END{print $4}' > PIPELINE/normMaxMincollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "percolationThresholdJumps*.csv" | xargs -n1 awk -F "," 'END{print $1}' > PIPELINE/percolationCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "MeanDropsBetweenStepsForAllFramesIn*.csv" | xargs -n1 awk -F "," 'END{print $2}' > PIPELINE/walkerDegreeCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_MeanD_WS.csv" |  xargs -n1 awk -F "," 'END{print $2}' > PIPELINE/meanDegreeWSCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*_CoeffVarD_WS.csv" | xargs -n1 awk -F "," 'END{print $2}' > PIPELINE/cvDegreeWSCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "summaryStatsInterMitoDist*" | xargs -n1 awk -F "," 'END{print $3}' > PIPELINE/meanInterMitoDistCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "summaryStatsInterMitoDist*" |  xargs -n1 awk -F "," 'END{print $2}' > PIPELINE/cvInterMitoDistCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "averageOverAllSpeedsAllFrames.csv" | xargs tail -1 -q > PIPELINE/meanSpeedCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStats_*" | xargs -n1 awk -F "," 'END{print $2}' > PIPELINE/maxCHCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStats_*" | xargs -n1 awk -F "," 'END{print $3}' > PIPELINE/minCHCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStats_*" | xargs -n1 awk -F "," 'END{print $4}' > PIPELINE/meanCHCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStats_*" | xargs -n1 awk -F "," 'END{print $5}' > PIPELINE/cvCHCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "associationtimeMeanIn*" | xargs -n1 awk -F "," 'END{print $2}' > PIPELINE/assocTimeCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStatsAsRate_*" | xargs -n1 awk -F "," 'END{print $2}' > PIPELINE/maxCHRateCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStatsAsRate_*" | xargs -n1 awk -F "," 'END{print $3}' > PIPELINE/minCHRateCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStatsAsRate_*" | xargs -n1 awk -F "," 'END{print $4}' > PIPELINE/meanCHRateCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "ConvexHullSummStatsAsRate_*" | xargs -n1 awk -F "," 'END{print $5}' > PIPELINE/cvCHRateCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "averageDistsOverNetworksForAllFrames_WS.csv" | xargs -n1 awk -F "," 'END{print $2}'> PIPELINE/AverageDistsWScollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "*averageNumberOfConnectedNeighbours.csv" | xargs -n1 awk -F "," 'END{print $2}'> PIPELINE/avConnectedNeighboursWSCollation.txt
find PIPELINE/mitoGFP-TRACKMATERUNS  PIPELINE/FRIENDLY-TRACKMATERUNS  PIPELINE/simulation PIPELINE/original_nulls PIPELINE/bio_motivated PIPELINE/stripped_down  PIPELINE/random_choice PIPELINE/IndependantVideos-TRACKMATE -name "avNetworkEfficiency_WS.csv" | xargs -n1 awk -F "," 'END{print $2}'> PIPELINE/NetworkEfficiencyWSCollation.txt

paste -d' '  PIPELINE/FrameNocollation.txt PIPELINE/CCcollation.txt   PIPELINE/propMaxCCcollation.txt PIPELINE/normPropMaxCCcollation.txt  PIPELINE/MaxMincollation.txt   PIPELINE/normMaxMincollation.txt   PIPELINE/percolationCollation.txt   PIPELINE/walkerDegreeCollation.txt   PIPELINE/meanDegreeWSCollation.txt   PIPELINE/cvDegreeWSCollation.txt   PIPELINE/meanInterMitoDistCollation.txt   PIPELINE/cvInterMitoDistCollation.txt   PIPELINE/meanSpeedCollation.txt   PIPELINE/maxCHCollation.txt   PIPELINE/minCHCollation.txt   PIPELINE/meanCHCollation.txt   PIPELINE/cvCHCollation.txt   PIPELINE/assocTimeCollation.txt  PIPELINE/maxCHRateCollation.txt PIPELINE/minCHRateCollation.txt PIPELINE/meanCHRateCollation.txt  PIPELINE/cvCHRateCollation.txt PIPELINE/AverageDistsWScollation.txt PIPELINE/avConnectedNeighboursWSCollation.txt PIPELINE/NetworkEfficiencyWSCollation.txt > PIPELINE/StatsTable.txt
